<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://greenhat.com/model" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="SAP_DATAM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cKMNummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geschaeftspartner" lowerBound="1" eType="//GeschaeftspartnerType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertragLesens" lowerBound="1" upperBound="-1" eType="//VertragLesenType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aktivitaet" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeschaeftspartnerType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschaeftspartnerNummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cKMNummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partnerKategorie" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partnerTyp" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" lowerBound="1" eType="//PersonType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adresse" lowerBound="1" eType="//AdresseType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kontaktangaben" lowerBound="1" eType="//KontaktangabenType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anrede" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vorname" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geburtsdatum" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdresseType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adressTyp" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strasse" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postfachOhneNummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pLZ" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ort" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="land" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KontaktangabenType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="korrespondenzSprache" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="telefon" lowerBound="1" eType="//TelefonType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="emailAdresse" eType="//EmailAdresseType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TelefonType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telefonNummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="land" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertragLesenType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leistungsvertrag" lowerBound="1" eType="//LeistungsvertragType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verknuepftesGAs" upperBound="-1" eType="//VerknuepftesGAType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeistungsvertragType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertragsnummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dienststellenCode" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vonDatum" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bisDatum" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hauptzahlungsmittel" eType="//HauptzahlungsmittelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leistungsvertragPosition" lowerBound="1" eType="//LeistungsvertragPositionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partners" lowerBound="1" upperBound="-1" eType="//PartnerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HauptzahlungsmittelType"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeistungsvertragPositionType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artikel" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leistungsID" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vonDatum" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bisDatum" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartnerType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partnerfunktion" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geschaeftspartner" lowerBound="1" eType="//GeschaeftspartnerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmailAdresseType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAdresse" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerknuepftesGAType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="istBasisGA" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertragsnummer" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
